### ISSUE TITLE
Circular Progress bar Invalid Resx file?

### ISSUE THREAD

**Issue by Madman456** [falahati/CircularProgressBar#7] opened 2017-02-23 01:30 UTC
So i downloaded a Circular ProgressBar package with nuget, when i drag the component onto the form, and try to run the program, i get this error and idk how to fix it.  I'm using visual studio 2015 community edition, and ideas?
![progress error](https://cloud.githubusercontent.com/assets/25969018/23240844/b204a908-f93d-11e6-8c45-a7bc18ce8589.PNG)

**Comment by falahati** [comment] 2017-02-23 22:00
This is wired, try removing the library from your project, delete the "packages" folder in your solution directory and add the library again to see if this fixes the problem. If not, report here so I go investigate it further.

**Comment by Madman456** [comment] 2017-02-24 00:24
I just did it, but got the same results :(

**Comment by Madman456** [comment] 2017-02-24 00:24
whoops didn't mean to close the topic lol

**Comment by pedhirect** [comment] 2017-03-10 11:41
i'm also facing the same problem, when i'm using visual basic.Its working properly in C#.

Please reply 
Thanks in advance

**Comment by falahati** [comment] 2017-03-12 21:08
I can't reproduce it,

Please send me a sample project files that you have this issue with and mention your .NetFramework version you are using.

Thanks

**Comment by falahati** [comment] 2017-03-12 22:17
Nevermind,

It seems that VB.Net can't deserialize the `AnimationFunctions.Function` delegate as its `mscorlib` is different from C#.

Anyway, the fastest fix is to edit your `Form.Designer.vb` and set all `CircularProgressBar.AnimationFunction` properties to `Nothing`. Funny enough, I forgot to actually use this property, so no harm setting it to `Nothing`.
You also need to edit your `Form.resx` file and remove all serialized information about this property.

In the next release, I address this issue by using an `Enum` instead of direct using of `AnimationFunctions.Function` delegate and a method to set custom animation functions. Also, actually using its value.

Thanks

**Comment by falahati** [comment] 2017-03-14 22:47
Please update the package and confirm it.

**Comment by pedhirect** [comment] 2017-03-15 03:48
Dear falahati,

i'm unable to add .dll file in 'toolbar'.So,i tried your sample program found this error.
![image](https://cloud.githubusercontent.com/assets/26325374/23932816/3806e1f6-0960-11e7-9038-6d4886c4835c.png)
Am i doing something wrong??
Guide me

Thanks and regard
pedhirect

**Comment by falahati** [comment] 2017-03-16 16:17
Please check again, there was indeed a problem with invalid assembly culture data resulted in DLL detected as a satellite assembly.

**Comment by pedhirect** [comment] 2017-03-17 03:30
Still facing the Same Problem.

**Comment by falahati** [comment] 2017-05-13 13:50
Based on the #9, It seems that if you remove leftovers from the last version before or after updating to the latest version, the library works ok. So I close this issue. Please consider reading the other issue about the exact lines you need to remove.

**Closed as completed by falahati** 2017-05-13 13:50 UTC
Labels: bug, enhancement
