### ISSUE TITLE
Could not load file or assembly 'WinFormAnimation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.The system cannot find the file specified.

### ISSUE THREAD

**Issue by OguzKahramn** [falahati/CircularProgressBar#30] opened 2022-01-14 06:18 UTC
Hello. After I downloaded the package via NuGet Packet Manager, I am getting the error has been attached although winFormAnimation.dll is in my references. The program works correctly but I cannot see the form in [Design] section. What can be the solution for this error? I deleted package and downloaded it again but it did not help. Thank you in advance. 
![error12](https://user-images.githubusercontent.com/60695165/149460931-282b4bd6-86bc-4da4-be10-a226eca2f211.png)
![references](https://user-images.githubusercontent.com/60695165/149460932-ff245661-9291-4765-b185-53ac468b21f3.png)

**Comment by falahati** [comment] 2022-01-14 11:27
Duplicate of #21 and #10 I think

**Closed as completed** 2022-08-02 11:19 UTC
